const goalInput=document.getElementById('goalInput'), startBtn=document.getElementById('startBtn'), welcome=document.getElementById('welcomeView'), study=document.getElementById('studyView'), messages=document.getElementById('messages'), answerInput=document.getElementById('answerInput'), sendBtn=document.getElementById('sendBtn'), pathList=document.getElementById('pathList'), progress=document.getElementById('progress'), fileInput=document.getElementById('fileInput'), fileName=document.getElementById('fileName'), toast=document.getElementById('toast');
let step=0, sessionId=null; const steps=['理解函数是什么','参数与返回值','条件与循环','列表与字典','做一个小项目'];
function addMsg(text,type='ai'){const el=document.createElement('div');el.className='message '+type;el.innerHTML=`<div class="msg-avatar">${type==='ai'?'✦':'你'}</div><div class="bubble">${text}</div>`;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
function renderPath(){pathList.innerHTML=steps.map((s,i)=>`<div class="path-item ${i<step?'done':''} ${i===step?'current':''}"><div class="step">${i<step?'✓':i+1}</div><div>${s}${i===step?'<small style="display:block;color:#aaa;font-weight:400;margin-top:4px">正在学习</small>':''}</div></div>`).join('');progress.textContent=`${Math.min(step+1,steps.length)} / ${steps.length}`}
async function save(patch){if(!sessionId)return;await fetch('/api/sessions/'+sessionId,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)})}
async function start(){const goal=goalInput.value.trim()||'Python 基础';const title=goal.replace(/^我想(学会|学习|入门|看懂)/,'').trim()||'Python 基础';document.getElementById('pageTitle').textContent=title;welcome.classList.add('hidden');study.classList.remove('hidden');step=0;renderPath();messages.innerHTML='';const first=`太好了，我们就从「${steps[0]}」开始。<br><br>先不用记定义：你可以把<strong>函数</strong>想成一个会重复工作的“小机器”。你把输入交给它，它会按照规则给你一个结果。<br><br><b>试着用自己的话说说看：函数为什么有用？</b>`;addMsg(first);const s=await (await fetch('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,goal,steps,messages:[{type:'ai',text:first}]})})).json();sessionId=s.id;toastMsg('已保存到本地学习空间')}
startBtn.addEventListener('click',start);document.getElementById('newBtn').addEventListener('click',()=>{study.classList.add('hidden');welcome.classList.remove('hidden');goalInput.focus()});document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>{goalInput.value=b.dataset.goal;goalInput.focus()}));fileInput.addEventListener('change',()=>{if(fileInput.files[0]){fileName.textContent='已选择：'+fileInput.files[0].name;goalInput.value='我想学懂这份教材'}});
function toastMsg(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
async function send(){const text=answerInput.value.trim();if(!text)return;addMsg(text,'user');answerInput.value='';const replies=['回答得不错！你抓住了“复用”这个关键。函数让我们把一组操作封装起来，需要时只调用一次。接下来看看输入和输出。<br><br><b>如果一个函数没有返回值，你觉得它还能有用吗？</b>','很好的思考。没有返回值的函数也可以完成动作，比如打印、保存文件。现在我们进入下一个小节：条件与循环。<br><br><b>你在生活中见过哪些“满足条件才做某事”的例子？</b>','你已经建立起基础直觉了。我们继续把这些概念组合起来，最后会做一个小练习。<br><br><b>准备好后告诉我，或者输入“继续”。</b>'];step=Math.min(step+1,steps.length-1);renderPath();const reply=replies[Math.min(step-1,replies.length-1)];addMsg(reply);await save({step,messages:[...messages.querySelectorAll('.message')].map(x=>({type:x.classList.contains('user')?'user':'ai',text:x.querySelector('.bubble').innerHTML}))});toastMsg('进度已保存')}
sendBtn.addEventListener('click',send);answerInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
